# Generated by Django 3.0.7 on 2020-06-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_ratings', '0003_auto_20160721_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='review',
            field=models.TextField(null=True),
        ),
    ]
