# Generated by Django 3.0.7 on 2020-06-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_ratings', '0004_userrating_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userrating', name='score', field=models.SmallIntegerField(),
        ),
    ]
