# Generated by Django 3.0.7 on 2020-06-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_ratings', '0005_auto_20200615_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating', name='total', field=models.IntegerField(default=0),
        ),
    ]
