# Generated by Django 3.1.5 on 2021-01-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_ratings', '0006_auto_20200615_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rank',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
